export const FETCH_REQUEST_LISTING = 'FETCH_REQUEST_LISTING';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';
export const FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE';
export const FETCHING_PERSON = 'FETCHING_PERSON'; 
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_FAILURE = 'FETCH_PERSON_FAILURE';
export const EMPTY_LIST = 'EMPTY_LIST';
export const ADD_NEW_USER = 'ADD_NEW_USER';